# Generated by Django 5.1.4 on 2025-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotdotcom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoshoottable',
            name='Type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
