# Generated by Django 5.1.4 on 2025-01-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotdotcom', '0002_photoshoottable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='amalgamationtable',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
