# Generated by Django 5.1.4 on 2025-01-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotdotcom', '0003_amalgamationtable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspottable',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
