# Generated by Django 5.1.4 on 2025-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotdotcom', '0004_parkingspottable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspottable',
            name='NoParking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
